name: i-mae
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.1.74
  - matplotlib
  - numpy
  - python=3.9.7
  - pytorch=1.9.0
  - setuptools==59.5.0
  - tensorboard=1.15.0
  - timm
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - tqdm
  - wandb
